exports.urlShortener	= require('./shortener')
exports.translation		= require('./translation')
exports.menuId			= require('./menu')
exports.images			= require('./images')
exports.api				= require('./api')
